### ISSUE TITLE
Allow parenting to toggle multiple layers at once.

### ISSUE THREAD

**Issue by keiranlovett** [shinobushiva/Unity-ObjectLayer#1]
An addition to the ObjectLayer to allow layers to be assigned a "parent" category that is reflected through the UI and the Objects themselves. When a parent layer visibility is toggled, all the layers assigned to that parent will inherit that visibility state.

**Comment by shinobushiva** [comment]
Thank you for your comment.
I have added hierarchical layering. Please try it.
